version: '3.7'

services:
  react-minddoc:
    hostname: react
    image: react-minddoc:1.0
    build:
      context: .
    container_name: react
    expose:
      - 80
    ports:
      - 8080:80
    restart: always
